import { VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.11.1:17',
  releaseNotes: {
    en_US: `Fixes the Sync Progress health check, and requires an up-to-date Bitcoin.

Electrs answers RPC only between indexing batches, so a momentary silence is normal — but the health check read any silence as an unbuilt index and displayed "Electrs is building its address index. This can take several hours on first run." on servers whose index was complete, sometimes for hours at a stretch. The check now retries before drawing a conclusion, and once the index has been built it never claims a rebuild again — reporting instead that Electrs is busy. If you saw the old message on a working server, nothing was wrong and there was never any need to reindex.

Electrs also needs pruning disabled on Bitcoin, and a block-download connection that only newer Bitcoin releases offer. The version Electrs required did not rule older releases out on every Bitcoin version line, so on an out-of-date Bitcoin the Auto-Configure task opened a form that could not be submitted, and came back no matter what you did. Electrs now requires the current revision of whichever Bitcoin version line you are on, so an out-of-date Bitcoin is reported as needing an update instead.`,
    es_ES: `Corrige la comprobación de estado Progreso de sincronización y exige un Bitcoin actualizado.

Electrs solo responde a las llamadas RPC entre lotes de indexación, por lo que un silencio momentáneo es normal; sin embargo, la comprobación interpretaba cualquier silencio como un índice sin construir y mostraba "Electrs está construyendo su índice de direcciones. Esto puede tardar varias horas en la primera ejecución." en servidores cuyo índice ya estaba completo, a veces durante horas seguidas. Ahora la comprobación reintenta antes de concluir y, una vez construido el índice, nunca vuelve a anunciar una reconstrucción: indica que Electrs está ocupado. Si vio el mensaje antiguo en un servidor que funcionaba, no ocurría nada malo y nunca hizo falta reindexar.

Electrs necesita además que la poda esté desactivada en Bitcoin, y una conexión de descarga de bloques que solo ofrecen las versiones más recientes de Bitcoin. La versión que Electrs exigía no descartaba las versiones antiguas en todas las líneas de versiones de Bitcoin, así que en un Bitcoin desactualizado la tarea Auto-Configurar abría un formulario que no se podía enviar y volvía a aparecer hiciera lo que hiciera. Ahora Electrs exige la revisión actual de la línea de versiones de Bitcoin que uses, de modo que un Bitcoin desactualizado se señala como pendiente de actualizar.`,
    de_DE: `Behebt die Zustandsprüfung „Synchronisierungsfortschritt“ und setzt ein aktuelles Bitcoin voraus.

Electrs beantwortet RPC-Aufrufe nur zwischen den Indizierungsdurchläufen, kurzes Schweigen ist also normal — die Prüfung wertete jedes Schweigen jedoch als fehlenden Index und zeigte „Electrs baut seinen Adressindex auf. Beim ersten Start kann dies mehrere Stunden dauern." auch auf Servern mit fertigem Index an, mitunter stundenlang. Die Prüfung fragt jetzt erneut nach, bevor sie ein Urteil fällt, und kündigt nach dem ersten fertigen Index nie wieder einen Neuaufbau an, sondern meldet, dass Electrs beschäftigt ist. Wer die alte Meldung auf einem laufenden Server gesehen hat: Es war nichts defekt, und eine Neuindizierung war nie nötig.

Electrs benötigt außerdem Bitcoin ohne Pruning sowie eine Verbindung zum Blockabruf, die nur neuere Bitcoin-Ausgaben bieten. Die von Electrs geforderte Version schloss ältere Ausgaben nicht auf jeder Bitcoin-Versionsreihe aus, sodass auf einem veralteten Bitcoin die Aufgabe „Auto-Konfiguration“ ein Formular öffnete, das sich nicht absenden ließ, und immer wieder zurückkam. Electrs verlangt jetzt die aktuelle Revision der von dir genutzten Bitcoin-Versionsreihe, sodass ein veraltetes Bitcoin stattdessen als aktualisierungsbedürftig gemeldet wird.`,
    pl_PL: `Naprawia kontrolę stanu „Postęp synchronizacji" i wymaga aktualnego Bitcoina.

Electrs odpowiada na wywołania RPC tylko pomiędzy partiami indeksowania, więc chwilowa cisza jest normalna — kontrola traktowała jednak każdą ciszę jako brak indeksu i wyświetlała „Electrs buduje swój indeks adresów. Przy pierwszym uruchomieniu może to potrwać kilka godzin." na serwerach z gotowym indeksem, czasem godzinami. Teraz kontrola ponawia próbę, zanim wyciągnie wniosek, a po zbudowaniu indeksu nigdy więcej nie ogłasza przebudowy — informuje, że Electrs jest zajęty. Jeśli widziałeś stary komunikat na działającym serwerze, nic nie było zepsute i ponowne indeksowanie nigdy nie było potrzebne.

Electrs wymaga też wyłączonego przycinania w Bitcoinie oraz połączenia do pobierania bloków, które oferują dopiero nowsze wydania Bitcoina. Wersja wymagana przez Electrs nie wykluczała starszych wydań na każdej linii wydań Bitcoina, więc na nieaktualnym Bitcoinie zadanie Auto-Konfiguracja otwierało formularz, którego nie dało się wysłać, i wracało niezależnie od podjętych działań. Electrs wymaga teraz bieżącej rewizji tej linii wydań Bitcoina, z której korzystasz, więc nieaktualny Bitcoin jest zgłaszany jako wymagający aktualizacji.`,
    fr_FR: `Corrige le contrôle d'état « Progression de la synchronisation » et exige un Bitcoin à jour.

Electrs ne répond aux appels RPC qu'entre deux lots d'indexation : un silence momentané est donc normal. Le contrôle interprétait pourtant tout silence comme un index non construit et affichait « Electrs est en train de construire son index d'adresses. Cela peut prendre plusieurs heures lors de la première exécution. » sur des serveurs dont l'index était complet, parfois pendant des heures. Le contrôle réessaie désormais avant de conclure et, une fois l'index construit, n'annonce plus jamais de reconstruction : il indique qu'Electrs est occupé. Si vous avez vu l'ancien message sur un serveur fonctionnel, rien n'était cassé et il n'a jamais été nécessaire de réindexer.

Electrs a également besoin que l'élagage soit désactivé sur Bitcoin, ainsi que d'une connexion de téléchargement des blocs que seules les versions récentes de Bitcoin proposent. La version exigée par Electrs n'écartait pas les anciennes versions sur chaque ligne de versions de Bitcoin : sur un Bitcoin obsolète, la tâche Auto-Configuration ouvrait un formulaire impossible à envoyer et revenait quoi que vous fassiez. Electrs exige désormais la révision actuelle de la ligne de versions de Bitcoin que vous utilisez, de sorte qu'un Bitcoin obsolète est signalé comme devant être mis à jour.`,
  },
  migrations: {},
})
